services:
  cheshire-cat-core:
    build:
      context: ./core
    container_name: cheshire_cat_core
    # Uncomment the two lines below to use your .env (see .env.example)
    #env_file:
    #  - .env
    ports:
      - ${CCAT_CORE_PORT:-1865}:80
      - 5678:5678 # only for development purposes (take away in production)
    extra_hosts:
      - "host.docker.internal:host-gateway" # This add an entry to /etc/hosts file in the container mapping host.docker.internal to the host machine IP addr, allowing the container to access services running on the host, not only on Win and Mac but also Linux. See https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host and https://docs.docker.com/reference/cli/docker/container/run/#add-host
    environment:
      # Timezone
      - TZ=${CCAT_TIMEZONE:-UTC}
      # Pass the Redis password directly
      - CCAT_REDIS_PASSWORD=${CCAT_REDIS_PASSWORD:-}
    volumes:
      - ./core:/app
    command:
      - python
      - "-m"
      - "cat.main"
    restart: unless-stopped

  redis:
    image: redis:7.4.1
    container_name: cheshire_cat_redis
    # Use conditional command based on whether password is set
    command: >
      sh -c '[ ! -z "$$CCAT_REDIS_PASSWORD" ] && 
      redis-server --requirepass "$$CCAT_REDIS_PASSWORD" ||
      redis-server'
    environment:
      - CCAT_REDIS_PASSWORD=${CCAT_REDIS_PASSWORD:-}
    ports:
      - ${CCAT_REDIS_PORT:-6379}:6379
    restart: unless-stopped
